In [1]:
import numpy as np

#tuple array of South, West, East and Midwest Regionals respectively, listed in #1 - 16 seed order
R1teams = (("Kansas", "Villanova", "Miami", "California", "Maryland", "Arizona", "Iowa", "Colorado", "Connecticut", "Temple", "Wichita State", "South Dakota State", "Hawaii", "Buffalo", "UNC Asheville", "Austin Peay"),
            ("Oregon", "Oklahoma", "Texan A&M", "Duke", "Baylor", "Texas", "Oregon State", "Saint Joseph's", "Cincinnatti", "VCU", "Northern Iowa", "Yale", "UNC Wilmington", "Green Bay", "Cal State Bakersfield", "Holy Cross"),
            ("North Carolina", "Xavier", "West Virginia", "Kentucky", "Indiana", "Notre Dame", "Wisconsin", "USC", "Providence", "Pittsburgh", "Michigan", "Chattanooga", "Stony Brook", "Stephen F Austin", "Weber State", "Florida Gulf Coast"), 
            ("Virginia", "Michigan State", "Utah", "Iowa State", "Purdue", "Seton Hall", "Dayton", "Texas Tech", "Butler", "Syracuse", "Gonzaga", "Ankansas-Little Rock", "Iona", "Fresno State", "Middle Tennessee", "Hampton"))

#Random number generator for first round of games (8 games x 4 conferences)
Rand1 = np.random.randint(100, size=(4, 8))

# Round 1 simulation 

if Rand1[0][0]>49:
    S1_1 = R1teams[0][0]
else:
    S1_1 = R1teams[0][1]

if Rand1[0][1]>49:
    S1_2 = R1teams[0][2]
else:
    S1_2 = R1teams[0][3]    

if Rand1[0][2]>49:
    S1_3 = R1teams[0][4]
else:
    S1_3 = R1teams[0][5]
    
if Rand1[0][3]>49:
    S1_4 = R1teams[0][6]
else:
    S1_4 = R1teams[0][7]    

if Rand1[0][4]>49:
    S1_5 = R1teams[0][8]
else:
    S1_5 = R1teams[0][9]    

if Rand1[0][5]>49:
    S1_6 = R1teams[0][10]
else:
    S1_6 = R1teams[0][11]    

if Rand1[0][6]>49:
    S1_7 = R1teams[0][12]
else:
    S1_7 = R1teams[0][13]    

if Rand1[0][7]>49:
    S1_8 = R1teams[0][14]
else:
    S1_8 = R1teams[0][15]    


    
if Rand1[1][0]>49:
    W1_1 = R1teams[1][0]
else:
    W1_1 = R1teams[1][1]

if Rand1[1][1]>49:
    W1_2 = R1teams[1][2]
else:
    W1_2 = R1teams[1][3]    

if Rand1[1][2]>49:
    W1_3 = R1teams[1][4]
else:
    W1_3 = R1teams[1][5]
    
if Rand1[1][3]>49:
    W1_4 = R1teams[1][6]
else:
    W1_4 = R1teams[1][7]    

if Rand1[1][4]>49:
    W1_5 = R1teams[1][8]
else:
    W1_5 = R1teams[1][9]    

if Rand1[1][5]>49:
    W1_6 = R1teams[1][10]
else:
    W1_6 = R1teams[1][11]    

if Rand1[1][6]>49:
    W1_7 = R1teams[1][12]
else:
    W1_7 = R1teams[1][13]    

if Rand1[1][7]>49:
    W1_8 = R1teams[1][14]
else:
    W1_8 = R1teams[1][15]    


    
if Rand1[2][0]>49:
    E1_1 = R1teams[2][0]
else:
    E1_1 = R1teams[2][1]

if Rand1[2][1]>49:
    E1_2 = R1teams[2][2]
else:
    E1_2 = R1teams[2][3]    

if Rand1[2][2]>49:
    E1_3 = R1teams[2][4]
else:
    E1_3 = R1teams[2][5]
    
if Rand1[2][3]>49:
    E1_4 = R1teams[2][6]
else:
    E1_4 = R1teams[2][7]    

if Rand1[2][4]>49:
    E1_5 = R1teams[2][8]
else:
    E1_5 = R1teams[2][9]    

if Rand1[2][5]>49:
    E1_6 = R1teams[2][10]
else:
    E1_6 = R1teams[2][11]    

if Rand1[2][6]>49:
    E1_7 = R1teams[2][12]
else:
    E1_7 = R1teams[2][13]    

if Rand1[2][7]>49:
    E1_8 = R1teams[2][14]
else:
    E1_8 = R1teams[2][15]    

    

if Rand1[3][0]>49:
    M1_1 = R1teams[3][0]
else:
    M1_1 = R1teams[3][1]

if Rand1[3][1]>49:
    M1_2 = R1teams[3][2]
else:
    M1_2 = R1teams[3][3]    

if Rand1[3][2]>49:
    M1_3 = R1teams[3][4]
else:
    M1_3 = R1teams[3][5]
    
if Rand1[3][3]>49:
    M1_4 = R1teams[3][6]
else:
    M1_4 = R1teams[3][7]    

if Rand1[3][4]>49:
    M1_5 = R1teams[3][8]
else:
    M1_5 = R1teams[3][9]    

if Rand1[3][5]>49:
    M1_6 = R1teams[3][10]
else:
    M1_6 = R1teams[3][11]    

if Rand1[3][6]>49:
    M1_7 = R1teams[3][12]
else:
    M1_7 = R1teams[3][13]    

if Rand1[3][7]>49:
    M1_8 = R1teams[3][14]
else:
    M1_8 = R1teams[3][15]    
    
    
# Winners of Round 1
R2teams1=[[S1_1, S1_2, S1_3, S1_4, S1_5, S1_6, S1_7, S1_8],
          [W1_1, W1_2, W1_3, W1_4, W1_5, W1_6, W1_7, W1_8],
          [E1_1, E1_2, E1_3, E1_4, E1_5, E1_6, E1_7, E1_8],
          [M1_1, M1_2, M1_3, M1_4, M1_5, M1_6, M1_7, M1_8]]    

Rand2 = np.random.randint(100, size=(4, 4))  #Random generator for second round (4 games x 4 conferences)

# Round 2 simulation 

if Rand2[0][0]>49:
    S2_1 = R2teams1[0][0]
else:
    S2_1 = R2teams1[0][1]

if Rand2[0][1]>49:
    S2_2 = R2teams1[0][2]
else:
    S2_2 = R2teams1[0][3]    

if Rand2[0][2]>49:
    S2_3 = R2teams1[0][4]
else:
    S2_3 = R2teams1[0][5]
    
if Rand2[0][3]>49:
    S2_4 = R2teams1[0][6]
else:
    S2_4 = R2teams1[0][7]    


    
if Rand2[1][0]>49:
    W2_1 = R2teams1[1][0]
else:
    W2_1 = R2teams1[1][1]

if Rand2[1][1]>49:
    W2_2 = R2teams1[1][2]
else:
    W2_2 = R2teams1[1][3]    

if Rand2[1][2]>49:
    W2_3 = R2teams1[1][4]
else:
    W2_3 = R2teams1[1][5]
    
if Rand2[1][3]>49:
    W2_4 = R2teams1[1][6]
else:
    W2_4 = R2teams1[1][7]    


    
if Rand2[2][0]>49:
    E2_1 = R2teams1[2][0]
else:
    E2_1 = R2teams1[2][1]

if Rand2[2][1]>49:
    E2_2 = R2teams1[2][2]
else:
    E2_2 = R2teams1[2][3]    

if Rand2[2][2]>49:
    E2_3 = R2teams1[2][4]
else:
    E2_3 = R2teams1[2][5]
    
if Rand2[2][3]>49:
    E2_4 = R2teams1[2][6]
else:
    E2_4 = R2teams1[2][7]    

    

if Rand2[3][0]>49:
    M2_1 = R2teams1[3][0]
else:
    M2_1 = R2teams1[3][1]

if Rand2[3][1]>49:
    M2_2 = R2teams1[3][2]
else:
    M2_2 = R2teams1[3][3]    

if Rand2[3][2]>49:
    M2_3 = R2teams1[3][4]
else:
    M2_3 = R2teams1[3][5]
    
if Rand2[3][3]>49:
    M2_4 = R2teams1[3][6]
else:
    M2_4 = R2teams1[3][7]    


# Winners of Round 2
R3teams=[[S2_1, S2_2, S2_3, S2_4],
          [W2_1, W2_2, W2_3, W2_4],
          [E2_1, E2_2, E2_3, E2_4],
          [M2_1, M2_2, M2_3, M2_4]]

Rand3 = np.random.randint(100, size=(4, 2))

# Round 3 (Sweet 16) simulation 

if Rand3[0][0]>49:
    S3_1 = R3teams[0][0]
else:
    S3_1 = R3teams[0][1]

if Rand3[0][1]>49:
    S3_2 = R3teams[0][2]
else:
    S3_2 = R3teams[0][3]    
 

    
if Rand3[1][0]>49:
    W3_1 = R3teams[1][0]
else:
    W3_1 = R3teams[1][1]

if Rand3[1][1]>49:
    W3_2 = R3teams[1][2]
else:
    W3_2 = R3teams[1][3]    
   

    
if Rand3[2][0]>49:
    E3_1 = R3teams[2][0]
else:
    E3_1 = R3teams[2][1]

if Rand3[2][1]>49:
    E3_2 = R3teams[2][2]
else:
    E3_2 = R3teams[2][3]    

    

if Rand3[3][0]>49:
    M3_1 = R3teams[3][0]
else:
    M3_1 = R3teams[3][1]

if Rand3[3][1]>49:
    M3_2 = R3teams[3][2]
else:
    M3_2 = R3teams[3][3]    

    
    
R4teams=[[S3_1, S3_2],
          [W3_1, W3_2],
          [E3_1, E3_2],
          [M3_1, M3_2]]    

Rand4 = np.random.randint(100, size=(4, 1))


# Round 4 (Elite 8) simulation 

if Rand4[0][0]>49:
    S4 = R4teams[0][0]
else:
    S4 = R4teams[0][1]

if Rand4[1][0]>49:
    W4 = R4teams[1][0]
else:
    W4 = R4teams[1][1]
    
if Rand4[2][0]>49:
    E4 = R4teams[2][0]
else:
    E4 = R4teams[2][1]
    
if Rand4[3][0]>49:
    M4 = R4teams[3][0]
else:
    M4 = R4teams[3][1]

    
    
R5teams=[[S4],
          [W4],
          [E4],
          [M4]]

Rand5 = np.random.randint(100, size=(2, 1))

# Round 5 (Final 4) simulation 

if Rand5[0][0]>49:
    F1 = R5teams[0][0]
else:
    F1 = R5teams[1][0]

if Rand5[1][0]>49:
    F2 = R5teams[2][0]
else:
    F2 = R5teams[3][0]


R6teams=[F1, F2]

Rand6 = np.random.randint(100, size=(1, 1))

# Round 5 (Championship) simulation 

if Rand6[0][0]>49:
    Winner = R6teams[0]
else:
    Winner = R6teams[1]


Champion = Winner


    


In [2]:
Rand1      # Checking output of numbers

array([[53, 87, 35,  3,  6, 17, 21, 24],
       [18, 41, 54, 30, 70, 47, 40, 17],
       [49,  6, 50, 33, 75, 44, 21, 37],
       [98, 62, 81, 47, 79, 95, 83, 78]])

In [3]:
R2teams1

[['Kansas',
  'Miami',
  'Arizona',
  'Colorado',
  'Temple',
  'South Dakota State',
  'Buffalo',
  'Austin Peay'],
 ['Oklahoma',
  'Duke',
  'Baylor',
  "Saint Joseph's",
  'Cincinnatti',
  'Yale',
  'Green Bay',
  'Holy Cross'],
 ['Xavier',
  'Kentucky',
  'Indiana',
  'USC',
  'Providence',
  'Chattanooga',
  'Stephen F Austin',
  'Florida Gulf Coast'],
 ['Virginia',
  'Utah',
  'Purdue',
  'Texas Tech',
  'Butler',
  'Gonzaga',
  'Iona',
  'Middle Tennessee']]

In [4]:
Rand2

array([[20, 54, 71,  5],
       [95, 77, 92,  1],
       [41,  5, 47, 11],
       [98, 70, 74, 95]])

In [5]:
R3teams

[['Miami', 'Arizona', 'Temple', 'Austin Peay'],
 ['Oklahoma', 'Baylor', 'Cincinnatti', 'Holy Cross'],
 ['Kentucky', 'USC', 'Chattanooga', 'Florida Gulf Coast'],
 ['Virginia', 'Purdue', 'Butler', 'Iona']]

In [6]:
Rand3

array([[45, 38],
       [56, 18],
       [45, 25],
       [45, 36]])

In [7]:
R4teams

[['Arizona', 'Austin Peay'],
 ['Oklahoma', 'Holy Cross'],
 ['USC', 'Florida Gulf Coast'],
 ['Purdue', 'Iona']]

In [8]:
Rand4

array([[93],
       [89],
       [52],
       [53]])

In [9]:
R5teams

[['Arizona'], ['Oklahoma'], ['USC'], ['Purdue']]

In [10]:
Rand5

array([[13],
       [90]])

In [11]:
R6teams

['Oklahoma', 'USC']

In [12]:
Rand6

array([[45]])

In [13]:
Champion

'USC'